### ISSUE TITLE
Image Files and Reference TEXT files are out of sync

### ISSUE THREAD

**Issue by prabhuomkar** [msn199959/Logo-2k-plus-Dataset#1]
- Images are in folders having names both in English and Chinese, translation doesn't work for finding the exact folder for the class
- Image file names and filenames in images.txt and train_test_lable.txt both are out of order numerically

Questions:
- How can we parse the txt file to extract and read images?
- Is there a file which supports reading both reference txt files and the image files.

**Comment by msn199959** [comment]
Thank you for your feedback. We have checked and uploaded the new data set, which may take some time. Thank you for your reminding.

**Comment by msn199959** [comment]
> * Images are in folders having names both in English and Chinese, translation doesn't work for finding the exact folder for the class
> * Image file names and filenames in images.txt and train_test_lable.txt both are out of order numerically
> 
> Questions:
> 
> * How can we parse the txt file to extract and read images?
> * Is there a file which supports reading both reference txt files and the image files.
Thank you for your feedback. We have checked and uploaded the new data set, which may take some time. Thank you for your reminding.

**Comment by msn199959** [comment]
> * Images are in folders having names both in English and Chinese, translation doesn't work for finding the exact folder for the class
> * Image file names and filenames in images.txt and train_test_lable.txt both are out of order numerically
> 
> Questions:
> 
> * How can we parse the txt file to extract and read images?
> * Is there a file which supports reading both reference txt files and the image files.

Thank you for your feedback. We have checked and uploaded the new data set, which may take some time. Thank you for your reminding.

**Comment by prabhuomkar** [comment]
- Is baidu link correct? As GDrive showed 1.5GB
And Baidu is showing 2.5GB.
- Any estimate of how much time it'll take for GDrive link to be available? 

Thanks, appreciate your prompt reply

**Comment by prabhuomkar** [comment]
Closing this since, Google Drive link was added.
Thanks!

**Comment by msn199959** [comment]
> Closing this since, Google Drive link was added.
> Thanks!

the latest dataset is uploaded, you can download from baidu or google drive. you ar welcome!

**Comment by andrewekhalel** [comment]
Hi,
I can't find the dataset link. Is it still available?

**Comment by prabhuomkar** [comment]
@andrewekhalel you can refer following:
## Logo-2k+ Dataset Download
 Logo-2k+ Dataset Website:
 http://www.victor.sdnu.edu.cn/datasets/Logo2K.htm

 Baidu Drive Download Link: 
 https://pan.baidu.com/s/1NuwYPKkZoR0BksFANDJGKQ  password: zxf0 

 Google Drive Download Link: 
 https://drive.google.com/open?id=1PTA24UTZcsnzXPN1gmV0_lRg3lMHqwp6

**Comment by msn199959** [comment]
Sorry , the links were deleted by mistake. I re-uploaded again just now, you&nbsp;can&nbsp;have a try;)&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrew Khalel"<notifications@github.com&gt;; 
发送时间: 2020年3月17日(星期二) 下午5:24
收件人: "msn199959/Logo-2k-plus-Dataset"<Logo-2k-plus-Dataset@noreply.github.com&gt;; 
抄送: "CURRY"<969081947@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [msn199959/Logo-2k-plus-Dataset] Image Files and Reference TEXT files are out of sync (#1)





 
Hi,
 I can't find the dataset link. Is it still available?
