### ISSUE TITLE
70.7%/72.0% for NTS-Net ResNet50/ResNet152

### ISSUE THREAD

**Issue by youliangalex** [msn199959/Logo-2k-plus-Dataset#10]
Thanks to the authors to release the Logo-2K+ dataset.

In case one might be interested, we've trained the NTS-Net on this dataset, achieving ~70.7% with ResNet50 and ~72% with ResNet152. See https://github.com/elv-youliangyu/logo for details.

Edit: updated the latest training results for NTS-Net ResNet50/ResNet152

**Comment by pranaysawant** [comment]
Hi https://github.com/elv-youliangyu/logo is missing. show 404 error.
